-- ! INSERTING DATA

--! PREGUNTA
INSERT INTO pregunta (contenido) VALUES (LOWER('Es comida?'));
INSERT INTO pregunta (contenido) VALUES (LOWER('Es un objeto?'));
INSERT INTO pregunta (contenido) VALUES (LOWER('Es un animal?'));
INSERT INTO pregunta (contenido) VALUES (LOWER('Es un dispositivo tecnologico?'));
INSERT INTO pregunta (contenido) VALUES (LOWER('Es rapido?'));
INSERT INTO pregunta (contenido) VALUES (LOWER('Es mamifero?'));
INSERT INTO pregunta (contenido) VALUES (LOWER('Es grande?'));
INSERT INTO pregunta (contenido) VALUES (LOWER('Puede volar?'));
INSERT INTO pregunta (contenido) VALUES (LOWER('Puede saltar?'));
INSERT INTO pregunta (contenido) VALUES (LOWER('Produce luz?'));
INSERT INTO pregunta (contenido) VALUES (LOWER('Es azul?'));
INSERT INTO pregunta (contenido) VALUES (LOWER('Esta vivo?'));
INSERT INTO pregunta (contenido) VALUES (LOWER('Es comestible?'));
INSERT INTO pregunta (contenido) VALUES (LOWER('Es verde?'));
INSERT INTO pregunta (contenido) VALUES (LOWER('Tiene colmillos?'));
INSERT INTO pregunta (contenido) VALUES (LOWER('Es amarillo?'));
INSERT INTO pregunta (contenido) VALUES (LOWER('Es pegajoso?'));
INSERT INTO pregunta (contenido) VALUES (LOWER('Tiene patas?'));
INSERT INTO pregunta (contenido) VALUES (LOWER('Tiene branquias?'));
INSERT INTO pregunta (contenido) VALUES (LOWER('Se alimenta de peces?'));

--! CONCEPTO
INSERT INTO concepto (nombre) VALUES (LOWER('Telefono'));
INSERT INTO concepto (nombre) VALUES (LOWER('Pizza'));
INSERT INTO concepto (nombre) VALUES (LOWER('Avion'));
INSERT INTO concepto (nombre) VALUES (LOWER('Lampara'));
INSERT INTO concepto (nombre) VALUES (LOWER('Tarantula'));
INSERT INTO concepto (nombre) VALUES (LOWER('Limon'));
INSERT INTO concepto (nombre) VALUES (LOWER('Mango'));
INSERT INTO concepto (nombre) VALUES (LOWER('Narval'));

--! RESPUESTA
INSERT INTO respuesta VALUES (1,1,true);
INSERT INTO respuesta VALUES (2,1,false);
INSERT INTO respuesta VALUES (3,1,true);
INSERT INTO respuesta VALUES (4,1,true);
INSERT INTO respuesta VALUES (5,1,true);
INSERT INTO respuesta VALUES (6,1,false);
INSERT INTO respuesta VALUES (7,1,false);
INSERT INTO respuesta VALUES (8,1,true);
INSERT INTO respuesta VALUES (9,1,true);
INSERT INTO respuesta VALUES (10,1,true);
INSERT INTO respuesta VALUES (11,1,true);
INSERT INTO respuesta VALUES (12,1,true);
INSERT INTO respuesta VALUES (13,1,false);
INSERT INTO respuesta VALUES (14,1,true);
INSERT INTO respuesta VALUES (15,1,true);
INSERT INTO respuesta VALUES (16,1,true);
INSERT INTO respuesta VALUES (17,1,false);
INSERT INTO respuesta VALUES (18,1,true);
INSERT INTO respuesta VALUES (19,1,true);
INSERT INTO respuesta VALUES (20,1,false);

INSERT INTO respuesta VALUES (1,2,true);
INSERT INTO respuesta VALUES (2,2,false);
INSERT INTO respuesta VALUES (3,2,true);
INSERT INTO respuesta VALUES (4,2,true);
INSERT INTO respuesta VALUES (5,2,true);
INSERT INTO respuesta VALUES (6,2,false);
INSERT INTO respuesta VALUES (7,2,false);
INSERT INTO respuesta VALUES (8,2,true);
INSERT INTO respuesta VALUES (9,2,true);
INSERT INTO respuesta VALUES (10,2,true);
INSERT INTO respuesta VALUES (11,2,true);
INSERT INTO respuesta VALUES (12,2,true);
INSERT INTO respuesta VALUES (13,2,false);
INSERT INTO respuesta VALUES (14,2,true);
INSERT INTO respuesta VALUES (15,2,true);
INSERT INTO respuesta VALUES (16,2,true);
INSERT INTO respuesta VALUES (17,2,false);
INSERT INTO respuesta VALUES (18,2,true);
INSERT INTO respuesta VALUES (19,2,true);
INSERT INTO respuesta VALUES (20,2,false);

INSERT INTO respuesta VALUES (1,3,true);
INSERT INTO respuesta VALUES (2,3,false);
INSERT INTO respuesta VALUES (3,3,true);
INSERT INTO respuesta VALUES (4,3,true);
INSERT INTO respuesta VALUES (5,3,true);
INSERT INTO respuesta VALUES (6,3,false);
INSERT INTO respuesta VALUES (7,3,false);
INSERT INTO respuesta VALUES (8,3,true);
INSERT INTO respuesta VALUES (9,3,true);
INSERT INTO respuesta VALUES (10,3,true);
INSERT INTO respuesta VALUES (11,3,true);
INSERT INTO respuesta VALUES (12,3,true);
INSERT INTO respuesta VALUES (13,3,false);
INSERT INTO respuesta VALUES (14,3,true);
INSERT INTO respuesta VALUES (15,3,true);
INSERT INTO respuesta VALUES (16,3,true);
INSERT INTO respuesta VALUES (17,3,false);
INSERT INTO respuesta VALUES (18,3,true);
INSERT INTO respuesta VALUES (19,3,true);
INSERT INTO respuesta VALUES (20,3,false);

INSERT INTO respuesta VALUES (1,4,true);
INSERT INTO respuesta VALUES (2,4,false);
INSERT INTO respuesta VALUES (3,4,true);
INSERT INTO respuesta VALUES (4,4,true);
INSERT INTO respuesta VALUES (5,4,true);
INSERT INTO respuesta VALUES (6,4,false);
INSERT INTO respuesta VALUES (7,4,false);
INSERT INTO respuesta VALUES (8,4,true);
INSERT INTO respuesta VALUES (9,4,true);
INSERT INTO respuesta VALUES (10,4,true);
INSERT INTO respuesta VALUES (11,4,true);
INSERT INTO respuesta VALUES (12,4,true);
INSERT INTO respuesta VALUES (13,4,false);
INSERT INTO respuesta VALUES (14,4,true);
INSERT INTO respuesta VALUES (15,4,true);
INSERT INTO respuesta VALUES (16,4,true);
INSERT INTO respuesta VALUES (17,4,false);
INSERT INTO respuesta VALUES (18,4,true);
INSERT INTO respuesta VALUES (19,4,true);
INSERT INTO respuesta VALUES (20,4,false);

INSERT INTO respuesta VALUES (1,5,true);
INSERT INTO respuesta VALUES (2,5,false);
INSERT INTO respuesta VALUES (3,5,true);
INSERT INTO respuesta VALUES (4,5,true);
INSERT INTO respuesta VALUES (5,5,true);
INSERT INTO respuesta VALUES (6,5,false);
INSERT INTO respuesta VALUES (7,5,false);
INSERT INTO respuesta VALUES (8,5,true);
INSERT INTO respuesta VALUES (9,5,true);
INSERT INTO respuesta VALUES (10,5,true);
INSERT INTO respuesta VALUES (11,5,true);
INSERT INTO respuesta VALUES (12,5,true);
INSERT INTO respuesta VALUES (13,5,false);
INSERT INTO respuesta VALUES (14,5,true);
INSERT INTO respuesta VALUES (15,5,true);
INSERT INTO respuesta VALUES (16,5,true);
INSERT INTO respuesta VALUES (17,5,false);
INSERT INTO respuesta VALUES (18,5,true);
INSERT INTO respuesta VALUES (19,5,true);
INSERT INTO respuesta VALUES (20,5,false);
