--! Tabla Concepto
CREATE TABLE Concepto (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
    contenido VARCHAR(50) NOT NULL,
    --? CONSTRAINTS
    PRIMARY KEY (id)
);

--! Tabla Pregunta 
CREATE TABLE Pregunta (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
    contenido VARCHAR(80) NOT NULL,
    --? CONSTRAINTS
    PRIMARY KEY (id)
);

--! Tabla Respuesta (Sólo tendrá dos valores agregados --> boolean falso y true)
CREATE TABLE Respuesta (
    id_pregunta INTEGER NOT NULL,
    id_concepto INTEGER NOT NULL,
    contenido BOOLEAN DEFAULT true,
    --? CONSTRAINTS
    PRIMARY KEY (id_pregunta, id_concepto),
    FOREIGN KEY (id_pregunta) REFERENCES pregunta (id),
    FOREIGN KEY (id_concepto) REFERENCES concepto (id)
);